"""add_phase5_fields

Revision ID: 29aa758b05d7
Revises: 37cc37206003
Create Date: 2026-05-25 14:49:34.841873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29aa758b05d7'
down_revision: Union[str, None] = '37cc37206003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_steps', sa.Column('rollback_status', sa.String(length=20), nullable=True))
    op.add_column('task_steps', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('upgrade_tasks', sa.Column('failure_strategy', sa.String(length=20), nullable=True))
    op.add_column('upgrade_tasks', sa.Column('rollback_status', sa.String(length=20), nullable=True))
    op.add_column('upgrade_tasks', sa.Column('is_rollback', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upgrade_tasks', 'is_rollback')
    op.drop_column('upgrade_tasks', 'rollback_status')
    op.drop_column('upgrade_tasks', 'failure_strategy')
    op.drop_column('task_steps', 'retry_count')
    op.drop_column('task_steps', 'rollback_status')
    # ### end Alembic commands ###
