"""add ssh_password to service_nodes

Revision ID: 37cc37206003
Revises: b70785a01d04
Create Date: 2026-05-25 14:26:48.488541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cc37206003'
down_revision: Union[str, None] = 'b70785a01d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_nodes', sa.Column('ssh_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upgrade_packages', type_='unique')
    op.drop_column('service_nodes', 'ssh_password')
    # ### end Alembic commands ###
